// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl-UXZQtWkUYLH3Mj6Gfs_deWtx1ybXX4',
    appId: '1:578948223614:web:73a2e19025d477e151be2f',
    messagingSenderId: '578948223614',
    projectId: 'fruits-hup-2e997',
    authDomain: 'fruits-hup-2e997.firebaseapp.com',
    storageBucket: 'fruits-hup-2e997.firebasestorage.app',
    measurementId: 'G-XFKP4JED3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0jSI65DSruirjMdNbdLxplg41ebe4pg8',
    appId: '1:578948223614:android:2a35179bbdf4b91951be2f',
    messagingSenderId: '578948223614',
    projectId: 'fruits-hup-2e997',
    storageBucket: 'fruits-hup-2e997.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6srFbQWcm3bgZBvWuYe1dudm6ipoWq4o',
    appId: '1:578948223614:ios:4c5ed377b13b9e7551be2f',
    messagingSenderId: '578948223614',
    projectId: 'fruits-hup-2e997',
    storageBucket: 'fruits-hup-2e997.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6srFbQWcm3bgZBvWuYe1dudm6ipoWq4o',
    appId: '1:578948223614:ios:4c5ed377b13b9e7551be2f',
    messagingSenderId: '578948223614',
    projectId: 'fruits-hup-2e997',
    storageBucket: 'fruits-hup-2e997.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl-UXZQtWkUYLH3Mj6Gfs_deWtx1ybXX4',
    appId: '1:578948223614:web:65917474bca332eb51be2f',
    messagingSenderId: '578948223614',
    projectId: 'fruits-hup-2e997',
    authDomain: 'fruits-hup-2e997.firebaseapp.com',
    storageBucket: 'fruits-hup-2e997.firebasestorage.app',
    measurementId: 'G-X4DQD9DRJD',
  );
}
